name: Build LaTeX to PDF

on:
  push:
    tags: v*

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Build LaTeX and Set Output File Name
        uses: ./.github/actions/latexmk
        with:
          latex_file_name: 'main.tex'

      - name: Create and Upload a Release Asset
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./${{ env.LATEXMK_OUTPUT_PDF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
